config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :services
  devise_for :service_providers
  devise_for :users

  root 'static_pages#index'
  get 'registrations' => 'static_pages#registrations'  
  get 'myservices' => 'services#myservices'
  get 'birthday' => 'static_pages#birthday'

  resources :service

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, :all                   
    if user.has_role?(:admin)
      can :access, :rails_admin       
      can :dashboard                                  
      can :manage, :all    
  elsif user.has_role?(:moderator)
    can :access, :rails_admin       
    can :dashboard
    can :manage, [ServiceProvider]
end
end
end

app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :service_provider
	validates_presence_of :description, :location, :service_name, :price
end

app/models/service_provider.rb
class ServiceProvider < ActiveRecord::Base
has_many :services
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base

	ROLES = %i[admin moderator banned]
	
	def roles=(roles)
		roles = [*roles].map { |r| r.to_sym }
		self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
	end

	def roles
		ROLES.reject do |r|
			((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
		end
	end

	def has_role?(role)
		roles.include?(role)
	end

	def role?(base_role)
		ROLES.index(base_role.to_s) <=> ROLES.index(role)
	end

	def is?(role)
		roles.include?(role.to_s)
	end

	def self.find_first_by_auth_conditions(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
			where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
		else
			if conditions[:username].nil?
				where(conditions).first
			else
				where(username: conditions[:username]).first
			end
		end
	end
	validate :validate_username

	def validate_username
		if User.where(email: username).exists?
			errors.add(:username, :invalid)
		end
	end
	validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  attr_accessor :login
  def login=(login)
  	@login = login
  end

  def login
  	@login || self.username || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  class ApplicationController < ActionController::Base
    rescue_from CanCan::AccessDenied do |exception|
      redirect_to main_app.root_path, :alert => exception.message
    end
  end

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :username, :email, :password, :password_confirmation, roles: []]

    if params[:action] == 'update'
      devise_parameter_sanitizer.permit(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.permit(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

   def myservices
    @services = Service.where(:service_provider_id => current_service_provider.id)
  end

  # POST /services 
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.service_provider_id = current_service_provider.id    
    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:service_provider_id, :service_name, :description, :price, :location)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Ssup"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_footer.html.erb
    <footer class="footer-bs">
        <div class="row">
        	<div class="col-md-3 footer-brand animated fadeInLeft">
            	<h2>Logo</h2>
                <p>The party app is a collection of services helping you make the most epic party ever at the comfort of your home!</p>
                <p>The Party App © 2016, All rights reserved</p>
            </div>
        	<div class="col-md-4 col-sm-4 footer-nav animated fadeInUp">
            	<div class="col-md-6">
                    <ul class="list">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Contacts</a></li>
                        <li><a href="#">Terms & Condition</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        	<div class="col-md-2 col-sm-4 footer-social animated fadeInDown">
            	<h4>Follow Us</h4>
            	<ul>
                	<li><a href="#">Facebook</a></li>
                	<li><a href="#">Twitter</a></li>
                	<li><a href="#">Instagram</a></li>
                	<li><a href="#">RSS</a></li>
                </ul>
            </div>
        	<div class="col-md-3 footer-ns animated fadeInRight">
            	<h4>Newsletter</h4>
                <p>Don't worry, we won't spam you :)</p>
                <p>
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Email...">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Sign Up</button>
                      </span>
                    </div><!-- /input-group -->
                    <br><%= link_to "Work with us",new_service_provider_registration_path %>
                 </p>
            </div>
        </div>
    </footer>

app/views/layouts/_navbar.html.erb
<style>
	.nav > li{
		color: black;
	}

	.nav > li:hover{
		color: black;
	}

	.navbar-inverse .divider-vertical {
		border-right-color: transparent;
		border-left-color: transparent;
	}

	@media (max-width: 767px) {
		.navbar-collapse .nav > .divider-vertical {
			display: none;
			opacity: 0;
		}
	}
</style>
<!-- Navigation -->
<div class="custom_nav">
	<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Logo Here
				</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if current_user %>
					<li class="text-center"><a href='#'>Hi, <%= current_user.name %></a></li>
					<% end %>

					<% if current_user %>
					<ul class="text-center nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li class="text-center"><%= link_to "Account Settings", edit_user_registration_path %></li>
								<li class="text-center"><%= link_to "Logout", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %></li>
							</ul>
						</li>
					</ul>
					<% elsif current_service_provider%>
					<ul class="text-center nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li class="text-center"><%= link_to "My Services", myservices_path %></li>
								<li class="text-center"><%= link_to "Add Service", new_service_path %></li>
								<li class="text-center"><%= link_to "Logout", destroy_service_provider_session_path, method: :delete, confirm: "Are you sure?" %>
								</li>						
							</ul>
						</li>
					</ul>
					<% else %>
					<li class="text-center"><a href="/">Home<span class="sr-only">(current)</span></a></li>
					<li class="text-center"><%= link_to "Sign Up", new_user_registration_path %></li>
					<li class="text-center"><%= link_to "Login", new_user_registration_path %></li>
					<% end %>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<link href='https://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>


	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<!-- Latest compiled and minified CSS -->

	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
body{
		padding-top: 50px;
	}
	.col-centered{
		float: none;
		margin: 0 auto;
	}
</style>
<body style="background-color: #bf0060">	


	<%= render 'layouts/navbar' %>

	<div class="container">
		<div class='bg'></div>

	</div>
	<%= yield %>
</div>
	<%= render 'layouts/footer' %>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/services/_form.html.erb
<% if service_provider_signed_in? %>
  <%= form_for(@service) do |f| %>
    <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= f.label :service_name %><br>
      <%= f.text_field :service_name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.number_field :price %>
    </div>
    <div class="field">
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Service name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
    <tr>
      <td><%= service.service_name %></td>
      <td><%= service.description %></td>
      <td><%= service.price %></td>
      <td><%= service.location %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="text-center">
  <% if service_provider_signed_in? %>
  <%= link_to 'New Service', new_service_path %>
  <% else %>
  <a href="/service_providers/sign_in">Sign In</a> to add your services today!
   <% end %>
 </div>

app/views/services/myservices.html.erb
<% provide(:title, 'My Services') %>
<!DOCTYPE html>
<html>
<body>
	<div class="text-center">
		<h1> My Services </h1>
	</div>
	<table>
		<thead>
			<tr>
				<th>Service name</th>
				<th>Description</th>
				<th>Price</th>
				<th>Location</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @services.each do |service| %>
			<tr>
				<td><%= service.service_name %></td>
				<td><%= service.description %></td>
				<td><%= service.price %></td>
				<td><%= service.location %></td>
				<td><%= link_to 'Show', service %></td>
				<td><%= link_to 'Edit', edit_service_path(service) %></td>
				<td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</body>
</html>

app/views/services/new.html.erb
<div class="text-center">
	<% if service_provider_signed_in? %>
	<h1>New Service</h1>
	<%= render 'form' %>
	<% else %>
	<h1> This page is only for service providers, click below to go back </h1>
	<% end %>
	<%= link_to 'Back', services_path %>
</div>

app/views/services/show.html.erb
<% provide(:title, "#{@service.service_name}") %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Service name:</strong>
  <%= @service.service_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @service.location %>
</p>

<p>
  <strong>Service Provider:</strong>
  <%= @service.service_provider_id %>
</p>
<%= link_to 'Back', services_path %>

app/views/static_pages/birthday.html.erb
<% provide(:title, 'Birthdays') %>

app/views/static_pages/corporate.html.erb
<% provide(:title, 'Corporate') %>

app/views/static_pages/index.html.erb
<% provide(:title, 'Home') %>
<body id="page-top">
	<header class="tint">
		<div class="header-content">
			<div class="header-content-inner">
				<h1 id="homeHeading">Welcome to the party</h1>
				<hr>
				<p>Let's build you an unforgettable party!</p>
				<a href="#about" class="btn2 btn-primary btn-xl page-scroll">LET'S GO!</a>
			</div>
		</div>
	</header>
	<section class="bg-primary" id="about">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 text-center">
					<h2 class="section-heading">We've got what you need!</h2>
					<hr>
					<p class="text-faded">House Party, Corporate Party, Birthday Party and Weddings, at thePartyApp we help you build a party without you having to go around contacting people, we will make the reservations for you.</p><br><br>
					<a href="#portfolio" class="btn2 btn-primary btn-xl page-scroll">Let's get started</a>
				</div>
			</div>
		</div>
	</section>

	<section class="no-padding" id="portfolio">
		<div class="container-fluid">
			<div class="row no-gutter popup-gallery">
				<div class="col-lg-4 col-sm-6">
					<a href="birthday.html" class="portfolio-box">
						<%= image_tag 'parties/1.jpg', :class => 'img-responsive' %>                        
						<div class="portfolio-box-caption">
							<div class="portfolio-box-caption-content">
								<div class="project-name">
									Birthday Parties
								</div>
							</div>
						</div>
					</a>
				</div>
				<div class="col-lg-4 col-sm-6">
					<a href="img/portfolio/fullsize/1.jpg" class="portfolio-box">
						<%= image_tag 'parties/2.jpg', :class => 'img-responsive' %>                        
						<div class="portfolio-box-caption">
							<div class="portfolio-box-caption-content">
								<div class="project-name">
									Corporate Parties
								</div>
							</div>
						</div>
					</a>
				</div><div class="col-lg-4 col-sm-6">
					<a href="img/portfolio/fullsize/1.jpg" class="portfolio-box">
						<%= image_tag 'parties/3.jpg', :class => 'img-responsive' %>                        
						<div class="portfolio-box-caption">
							<div class="portfolio-box-caption-content">
								<div class="project-name">
									Weddings
								</div>
							</div>
						</div>
					</a>
				</div><div class="col-lg-4 col-sm-6">
					<a href="img/portfolio/fullsize/1.jpg" class="portfolio-box">
						<%= image_tag 'parties/4.jpg', :class => 'img-responsive' %>                        
						<div class="portfolio-box-caption">
							<div class="portfolio-box-caption-content">
								<div class="project-name">
									Casual Parties
								</div>
							</div>
						</div>
					</a>
				</div><div class="col-lg-4 col-sm-6">
					<a href="img/portfolio/fullsize/1.jpg" class="portfolio-box">
						<%= image_tag 'parties/5.jpg', :class => 'img-responsive' %>                        
						<div class="portfolio-box-caption">
							<div class="portfolio-box-caption-content">
								<div class="project-name">
									Project Name
								</div>
							</div>
						</div>
					</a>
				</div><div class="col-lg-4 col-sm-6">
					<a href="img/portfolio/fullsize/1.jpg" class="portfolio-box">
						<%= image_tag 'parties/6.jpg', :class => 'img-responsive' %>                        
						<div class="portfolio-box-caption">
							<div class="portfolio-box-caption-content">
								<div class="project-name">
									Project Name
								</div>
							</div>
						</div>
					</a>
				</div>
			</div>
		</div>
	</section>
</body>

app/views/static_pages/registrations.html.erb
<% provide(:title, "Registrations") %>
<!DOCTYPE html>
<html>
<body>
	<section id="home" data-type="background" data-speed="10">
		<article>
			<h1 class="text-center element" style="color:orange;padding-bottom:250px;border-color:red">How Does It Work?
			</h1>               
		</article>
		</section>   

		<section id="about" data-type="background" data-speed="10">
			<article>
				<div class="col-md-6" >
					<a href="/users/sign_in">
						<div class="nice-box">
						<p class="element"> User</p>
						</div>
					</div>
				</a>
				<div class="col-md-6">
					<a href="/service_providers/sign_in">
						<div class="nice-box">
						<p class="element">Service Providers</p>
						</div>	
					</a>
				</div>
			</article>
		</section>
	</body>
	</html>

app/views/static_pages/wedding.html.erb
<% provide(:title, 'Weddings') %>